language: ruby
rvm:
  - 2.2.0
  - 2.2.1
  - 2.2.2
  - jruby-9.0.0.0
  - ruby-head
jdk:
  - openjdk7 # for jruby
before_script: export JRUBY_OPTS="--server -J-Xss1024k -J-Xmx652m -J-XX:+UseConcMarkSweepGC"
matrix:
  allow_failures:
    - rvm: ruby-head
env: ARUBA_TIMEOUT=120 AHN_ENV=development
sudo: false
